FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=Malaoui
ENV N8N_BASIC_AUTH_PASSWORD=@l!ceSaGlisse
ENV GENERIC_TIMEZONE=Europe/Paris
ENV WEBHOOK_TUNNEL_URL=https://n8n-assistant.onrender.com

EXPOSE 5678
